### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by watsom27** [ryansolid/dom-expressions#167]
Hi,

When trying to use https://github.com/ryansolid/solid-ts-webpack (minus the TS) I get the following build error:

```
src/web/node_modules/babel-plugin-jsx-dom-expressions/index.js:228
  return config?.renderers?.find(r => r.name === renderer) ?? config;
                ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:84:7)
    at NativeCompileCache._moduleCompile (/Users/../.nvm/versions/node/v12.15.0/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/../.nvm/versions/node/v12.15.0/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/Users/../.nvm/versions/node/v12.15.0/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/../git/../apps/../src/web/node_modules/babel-preset-solid/index.js:1:84)
    at Module._compile (/Users/../.nvm/versions/node/v12.15.0/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

webpack 5.74.0 compiled with 1 error in 257 ms
```

<details>
<summary>Webpack Config</summary>

```
const path = require('path');

const config = {
    entry: {
        showConfirm: './src/entrypoints/showConfirm.jsx',
    },
    devServer: {
        contentBase: path.join(__dirname, 'dist'),
        publicPath: '/'
    },
    mode: 'development',
    resolve: {
        extensions: ['.tsx', '.ts', '.js', '.json']
    },
    module: {
        rules: [
            {
                test: /\.(js)x?$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        babelrc: false,
                        configFile: false,
                        presets: ['@babel/preset-env', 'solid'],
                        plugins: ['@babel/plugin-syntax-dynamic-import', '@babel/plugin-proposal-class-properties', '@babel/plugin-proposal-object-rest-spread'],
                    }
                }
            }
        ]
    }
}

module.exports = config
```
</details>

<details>
<summary>showConfirm.jsx</summary>

```
import { createSignal, onCleanup } from "solid-js";
import { render } from "solid-js/web";

const CountingComponent = () => {
    const [count, setCount] = createSignal(0);
    const interval = setInterval(
        () => setCount(c => c + 1),
        1000
    );

    onCleanup(() => clearInterval(interval));

    return <div>Count value is {count()}</div>;
};

render(() => <CountingComponent />, document.getElementById("app"));
```
</details>

Any help or advice would be appreciated!

Thanks

**Comment by ryansolid** [comment]
Oh weird this is a compiler error, not a runtime one. I'm usually pretty specific on not letting optional chaining `?.` get into runtime code but this is build time. I doubt it's webpack itself. What version of node are you using? I think this has been supported since Node 14. I think 16 is LTS.

Can you confirm that you are on node 14 or higher?

**Comment by watsom27** [comment]
Thank you very much for the quick response, node version was exactly the issue 🤦🏻 

For my work we use 12.15 (don't ask) and i had forgotten to change back to ~16.

Thanks again for you help. Everything is working perfect now :)
