### ISSUE TITLE
babel-plugin-jsx-dom-expressions: transformCondition is not defined error

### ISSUE THREAD

**Issue by btakita** [ryansolid/dom-expressions#171]
```
1:02:34 PM [vite] Internal server error: /home/brian/work/portfoliome/censible-core/node_modules/.pnpm/solid-start@0.1.8_bga3qpy3x2mcpb3xfn66l4kmc4/node_modules/solid-start/router.tsx: transformCondition is not defined
  Plugin: solid
  File: /home/brian/work/portfoliome/censible-core/node_modules/.pnpm/solid-start@0.1.8_bga3qpy3x2mcpb3xfn66l4kmc4/node_modules/solid-start/router.tsx?v=898a47ef
      at /home/brian/work/portfoliome/censible-core/node_modules/.pnpm/babel-plugin-jsx-dom-expressions@0.35.0_@babel+core@7.19.6/node_modules/babel-plugin-jsx-dom-expressions/index.js:1463:26
      at Array.forEach (<anonymous>)
      at processSpreads$1 (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/babel-plugin-jsx-dom-expressions@0.35.0_@babel+core@7.19.6/node_modules/babel-plugin-jsx-dom-expressions/index.js:1424:14)
      at transformAttributes$2 (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/babel-plugin-jsx-dom-expressions@0.35.0_@babel+core@7.19.6/node_modules/babel-plugin-jsx-dom-expressions/index.js:760:32)
      at transformElement$3 (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/babel-plugin-jsx-dom-expressions@0.35.0_@babel+core@7.19.6/node_modules/babel-plugin-jsx-dom-expressions/index.js:624:3)
      at transformElement (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/babel-plugin-jsx-dom-expressions@0.35.0_@babel+core@7.19.6/node_modules/babel-plugin-jsx-dom-expressions/index.js:3145:12)
      at transformNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/babel-plugin-jsx-dom-expressions@0.35.0_@babel+core@7.19.6/node_modules/babel-plugin-jsx-dom-expressions/index.js:3034:12)
      at PluginPass.transformJSX (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/babel-plugin-jsx-dom-expressions@0.35.0_@babel+core@7.19.6/node_modules/babel-plugin-jsx-dom-expressions/index.js:2995:18)
      at newFn (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/visitors.js:181:21)
      at NodePath._call (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:100:31)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitMultiple (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:74:17)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:131:19)
      at traverseNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:133:19)
      at traverseNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitMultiple (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:74:17)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:131:19)
      at traverseNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitMultiple (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:74:17)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:131:19)
      at traverseNode (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
      at NodePath.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/path/context.js:107:52)
      at TraversalContext.visitQueue (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:105:16)
      at TraversalContext.visitSingle (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:79:19)
      at TraversalContext.visit (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@babel+traverse@7.19.6/node_modules/@babel/traverse/lib/context.js:133:19)
```

**Comment by ryansolid** [comment]
Fixed in 0.35.1
